# Constants that are used in the project.

CAMERA_LOWER_HUE = 32
CAMERA_LOWER_SATURATION = 49
CAMERA_LOWER_VALUE = 40
CAMERA_UPPER_HUE = 69
CAMERA_UPPER_SATURATION = 255
CAMERA_UPPER_VALUE = 255

CAMERA_INDEX = 1
CAMERA_FRAME_WIDTH = 640
CAMERA_FRAME_HEIGHT = 360
CAMERA_FRAME_ROBOT_MAX_Y = 270
CAMERA_FRAMERATE = 90
CAMERA_FOCUS = 1
CAMERA_BUFFERSIZE = 2

STEPPER_COM_PORT = "COM3"
STEPPER_BAUDRATE = 115200

TABLE_MAX_X = 1885
TABLE_MAX_Y = 1820

SPEED_THRESHOLD = 20

MAX_PUCK_POSITION_BUFFER = 10

TABLE_CORNER_TOP_LEFT_X = 42
TABLE_CORNER_TOP_LEFT_Y = 66

TABLE_CORNER_TOP_RIGHT_X = 314
TABLE_CORNER_TOP_RIGHT_Y = 75

TABLE_CORNER_BOTTOM_RIGHT_X = 304
TABLE_CORNER_BOTTOM_RIGHT_Y = 556

TABLE_CORNER_BOTTOM_LEFT_X = 29
TABLE_CORNER_BOTTOM_LEFT_Y = 551

DEFENSIVE_LINE = 50
