# Constants that are used in the project.

CAMERA_LOWER_HUE = 32
CAMERA_LOWER_SATURATION = 90
CAMERA_LOWER_VALUE = 40
CAMERA_UPPER_HUE = 69
CAMERA_UPPER_SATURATION = 255
CAMERA_UPPER_VALUE = 255
CAMERA_PUCK_MAX_RADIUS = 25
CAMERA_PUCK_MIN_RADIUS = 7

CAMERA_ROBOT_LOWER_HUE = 170
CAMERA_ROBOT_LOWER_SATURATION = 100
CAMERA_ROBOT_LOWER_VALUE = 40
CAMERA_ROBOT_UPPER_HUE = 179
CAMERA_ROBOT_UPPER_SATURATION = 255
CAMERA_ROBOT_UPPER_VALUE = 180
CAMERA_ROBOT_MIN_RADIUS = 10
CAMERA_ROBOT_MAX_RADIUS = 30



CAMERA_INDEX=0
# Change the URL to "virtual" if you want to simulate the Camera using a pre-recorded video
CAMERA_STREAM_URL =  "virtual"  
CAMERA_FRAME_WIDTH = 640
CAMERA_FRAME_HEIGHT = 480
CAMERA_FRAME_ROBOT_MAX_Y = 270
CAMERA_FRAMERATE = 120.0
CAMERA_FOCUS = 1
CAMERA_BUFFERSIZE = 2

# Change to VIRTUAL_CAM = True, if you want to simulate the Camera using a pre-recorded video
VIRTUAL_CAM = True
# If True the VideoStream gets recorded and saved
RECORD_VIDEO = False

# The frequency at which the robot detection is done.
# The camera can be used to detect the robot every x frames.
CAMERA_ROBOT_DETECTION_FREQUENCY = 1

STEPPER_COM_PORT = "COM3"
STEPPER_BAUDRATE = 115200

TABLE_MAX_X = 1885
TABLE_MAX_Y = 1450      #ursprünglicher Wert: 1820

SPEED_THRESHOLD = 20

MAX_PUCK_POSITION_BUFFER = 10

TABLE_CORNER_TOP_LEFT_X = 22
TABLE_CORNER_TOP_LEFT_Y = 19

TABLE_CORNER_TOP_RIGHT_X = 391
TABLE_CORNER_TOP_RIGHT_Y = 18

TABLE_CORNER_BOTTOM_RIGHT_X = 428
TABLE_CORNER_BOTTOM_RIGHT_Y = 598

TABLE_CORNER_BOTTOM_LEFT_X = 27
TABLE_CORNER_BOTTOM_LEFT_Y = 623

DEFENSIVE_LINE = 20

ROBOT_HOME_Y = 70
ROBOT_DEFEND_Y = 110
ROBOT_HOME_X_CAM = CAMERA_FRAME_HEIGHT / 2

GORIGHT_MAX = TABLE_CORNER_BOTTOM_RIGHT_X - 70
GOLEFT_MAX = 70
GOFORWARD_MAX = 150

FRAME_PUCK_OUTLINE_COLOR = (0, 0, 255)
FRAME_ROBOT_OUTLINE_COLOR = (0, 255, 255)


HOME_POSITION_X = 942
HOME_POSITION_Y = 101