# Constants that are used in the project.

# Commented out values are for green puck.
# Current values are for blue paper puck.
CAMERA_LOWER_HUE = 37
CAMERA_LOWER_SATURATION = 49
CAMERA_LOWER_VALUE = 40
CAMERA_UPPER_HUE = 69
CAMERA_UPPER_SATURATION = 255
CAMERA_UPPER_VALUE = 255

CAMERA_INDEX = 2
CAMERA_FRAME_WIDTH = 640
CAMERA_FRAME_HEIGHT = 360
CAMERA_FRAMERATE = 60
CAMERA_FOCUS = 5
CAMERA_BUFFERSIZE = 2

STEPPER_COM_PORT = "COM3"
STEPPER_BAUDRATE = 115200

TABLE_MAX_X = 1960
TABLE_MAX_Y = 2900

SPEED_THRESHOLD = 50